// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8K2IIKQ_U3gwNXOFmE_IG8X59KktO5hM',
    appId: '1:610725352785:web:aae2bf0fcd609d223b2f70',
    messagingSenderId: '610725352785',
    projectId: 'flutter-chat-application-65f12',
    authDomain: 'flutter-chat-application-65f12.firebaseapp.com',
    storageBucket: 'flutter-chat-application-65f12.appspot.com',
    measurementId: 'G-JBTJGF3ESF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJzZdRyMIec1qilaQnjBURGBvkS6XTLSI',
    appId: '1:610725352785:android:c4272311dcfd08523b2f70',
    messagingSenderId: '610725352785',
    projectId: 'flutter-chat-application-65f12',
    storageBucket: 'flutter-chat-application-65f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kAu5vnHKSF2-TexxnbnFWwtXzJPZnxU',
    appId: '1:610725352785:ios:6729eb6aae7112c73b2f70',
    messagingSenderId: '610725352785',
    projectId: 'flutter-chat-application-65f12',
    storageBucket: 'flutter-chat-application-65f12.appspot.com',
    iosClientId: '610725352785-vouuc5gclkjpkn6f4e47d5qlpcigv1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kAu5vnHKSF2-TexxnbnFWwtXzJPZnxU',
    appId: '1:610725352785:ios:6729eb6aae7112c73b2f70',
    messagingSenderId: '610725352785',
    projectId: 'flutter-chat-application-65f12',
    storageBucket: 'flutter-chat-application-65f12.appspot.com',
    iosClientId: '610725352785-vouuc5gclkjpkn6f4e47d5qlpcigv1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
